name: Jest

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npx jest --verbose ./*\\.test.js --passWithNoTests
