(function(v,w,l,x,n,p,q,y,r,z,A,B,C,D,E,s,t,F,u,G,H,I,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,$,aa,ba,ca,da,ea,fa,ga,ha,ia,ja,ka,la,ma,e,f){Jmol.Console={buttons:{},buttonWidth:100,click:function(a){Jmol.Console.buttons[a].console.appletConsole.doAction(Jmol.Console.buttons[a])}};Jmol.Console.JSConsole=function(a){this.applet=a.vwr.applet;var c=this.id=this.applet._id+"_console",b=this;Jmol.Console.buttons[b.id]=b;b.appletConsole=a;b.input=a.input=new Jmol.Console.Input(b);b.output=a.output=new Jmol.Console.Output(b);
var d='<div id="$ID" class="jmolConsole" style="display:block;background-color:yellow;width:600px;height:362px;position:absolute;z-index:'+Jmol._z.console+'"><div id=$ID_title></div><div id=$ID_label1></div><div id=$ID_outputdiv style="position:relative;left:2px"></div><div id=$ID_inputdiv style="position:relative;left:2px"></div><div id=$ID_buttondiv></div></div>',g=function(a,b){b.console=a;b.id=c+"_"+b.label.replace(/\s/g,"_");Jmol.Console.buttons[b.id]=b;return b.html()},d=d.replace(/\$ID/g,c);
Jmol.$after("body",d);b.setContainer(Jmol._$(c));b.setPosition();b.dragBind(!0);d="&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"javascript:Jmol.Console.buttons['"+c+"'].setVisible(false)\">close</a>"+('&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:Jmol.script('+b.applet._id+",'help')\">help</a>");Jmol.$html(c+"_label1",d);Jmol.$html(c+"_inputdiv",'<textarea id="'+c+'_input" style="width:590px;height:100px"></textarea>');Jmol.$html(c+"_outputdiv",'<textarea id="'+c+'_output" style="width:590px;height:200px"></textarea>');
d=g(b,a.runButton)+g(b,a.loadButton)+g(b,a.clearInButton)+g(b,a.clearOutButton)+g(b,a.historyButton)+g(b,a.stateButton);Jmol.$html(c+"_buttondiv",d);Jmol.$bind("#"+c+"_input","keypress",function(a){b.input.keyPressed(a)});Jmol.$bind("#"+c+"_input","keyup",function(a){b.input.keyReleased(a)});Jmol.$bind("#"+c+"_input","mousedown touchstart",function(){b.ignoreMouse=!0});Jmol.$bind("#"+c+"_output","mousedown touchstart",function(){b.ignoreMouse=!0});b.setButton=function(a){return new Jmol.Console.Button(this,
a)};b.setVisible=function(a){a?this.container.show():this.container.hide();this.dragBind(a)};b.setTitle=function(){}};Jmol.Swing.setDraggable(Jmol.Console.JSConsole);Jmol.Console.Input=function(a){this.console=a;this.id=a.id+"_input";this.getText=function(){return Jmol.$val(this.id)};this.setText=function(a){null==a&&(a="");Jmol.$val(this.id,a)};this.keyPressed=function(a){var b=8!=a.keyCode&&9!=a.keyCode&&10!=a.keyCode&&13!=a.keyCode&&a.which==a.keyCode?0:a.keyCode,d=a.ctrlKey;13==b&&(b=10);var g=
this.console.appletConsole.processKey(b,401,d);d&&10==b&&this.setText(this.getText()+"\n");if(9==a.keyCode||9==b){if(a.preventDefault(),0==g){var e=this;setTimeout(function(){e.setText(e.getText()+"\t");Jmol.$focus(e.id)},10)}}else(1==(g&1)||a.which==a.keyCode&&8!=b&&10!=b&&32>a.keyCode||38==a.keyCode||40==a.keyCode)&&a.preventDefault()};this.keyReleased=function(a){var b=a.which,d=a.ctrlKey;13==b&&(b=10);38==b||40==b?(this.keyPressed(a),a.preventDefault()):1==(this.console.appletConsole.processKey(b,
402,d)&1)&&a.preventDefault()};this.getCaretPosition=function(){var a=Jmol._$(this.id)[0];if("selectionStart"in a)return a.selectionStart;if(!("selection"in document))return 0;a.focus();var b=document.selection.createRange(),d=document.selection.createRange().text.length;b.moveStart("character",-a.value.length);return b.text.length-d}};Jmol.Console.Output=function(a){this.id=a.id+"_output";this.getText=function(){return Jmol.$val(this.id)};this.setText=function(a){null==a&&(a="");Jmol.$val(this.id,
a)};this.append=function(a){this.setText(this.getText()+a);Jmol.$scrollTo(this.id,-1)}};Jmol.Console.Button=function(a){this.label=a};Jmol.Console.Button.prototype.addConsoleListener=function(a){this.appletConsole=a;Jmol.Console.buttons[this.id]=this};Jmol.Console.Button.prototype.html=function(){return'<input type="button" id="'+this.id+'" style="width:'+Jmol.Console.buttonWidth+'px" value="'+this.label+'" onClick="Jmol.Console.click(\''+this.id+"')\"/>"};l("J.console");u(J.console,"GenericTextArea");
l("J.console");n(["J.api.JmolAppConsoleInterface","$.JmolCallbackListener","java.util.Hashtable"],"J.console.GenericConsole","java.lang.Boolean JU.PT J.c.CBK J.i18n.GT JS.T JV.Viewer".split(" "),function(){c$=q(function(){this.label1=this.defaultMessage=this.loadButton=this.clearInButton=this.clearOutButton=this.stateButton=this.historyButton=this.runButton=this.editButton=this.menuMap=this.labels=this.vwr=this.output=this.input=null;this.nTab=0;this.incompleteCmd=null;p(this,arguments)},J.console,
"GenericConsole",null,[J.api.JmolAppConsoleInterface,J.api.JmolCallbackListener]);s(c$,function(){this.menuMap=new java.util.Hashtable});e(c$,"setViewer",function(a){this.vwr=a},"JV.Viewer");e(c$,"addButton",function(a,c){a.addConsoleListener(this);this.menuMap.put(c,a);return a},"J.api.JmolAbstractButton,~S");e(c$,"getLabel1",function(){return null});e(c$,"setupLabels",function(){this.labels.put("help",J.i18n.GT._("&Help"));this.labels.put("search",J.i18n.GT._("&Search..."));this.labels.put("commands",
J.i18n.GT._("&Commands"));this.labels.put("functions",J.i18n.GT._("Math &Functions"));this.labels.put("parameters",J.i18n.GT._("Set &Parameters"));this.labels.put("more",J.i18n.GT._("&More"));this.labels.put("Editor",J.i18n.GT._("Editor"));this.labels.put("State",J.i18n.GT._("State"));this.labels.put("Run",J.i18n.GT._("Run"));this.labels.put("Clear Output",J.i18n.GT._("Clear Output"));this.labels.put("Clear Input",J.i18n.GT._("Clear Input"));this.labels.put("History",J.i18n.GT._("History"));this.labels.put("Load",
J.i18n.GT._("Load"));this.labels.put("label1",J.i18n.GT._("press CTRL-ENTER for new line or paste model data and press Load"));this.labels.put("default",J.i18n.GT._("Messages will appear here. Enter commands in the box below. Click the console Help menu item for on-line help, which will appear in a new browser window."))});e(c$,"setLabels",function(){var a=J.i18n.GT.setDoTranslate(!0);this.editButton=this.setButton("Editor");this.stateButton=this.setButton("State");this.runButton=this.setButton("Run");
this.clearOutButton=this.setButton("Clear Output");this.clearInButton=this.setButton("Clear Input");this.historyButton=this.setButton("History");this.loadButton=this.setButton("Load");this.defaultMessage=this.getLabel("default");this.setTitle();J.i18n.GT.setDoTranslate(a)});e(c$,"getLabel",function(a){null==this.labels&&(this.labels=new java.util.Hashtable,this.labels.put("title",J.i18n.GT._("Jmol Script Console")+" "+JV.Viewer.getJmolVersion()),this.setupLabels());return this.labels.get(a)},"~S");
e(c$,"displayConsole",function(){this.layoutWindow(null);this.outputMsg(this.defaultMessage)});e(c$,"updateLabels",function(){});e(c$,"completeCommand",function(a){if(0==a.length)return null;var c=0>=this.nTab||null==this.incompleteCmd?a:this.incompleteCmd;this.incompleteCmd=c;a=J.console.GenericConsole.splitCommandLine(a);if(null==a)return null;var b=null==a[2],d=null!=a[3],g=a[b?1:2],e=a[1];if(0==g.length)return null;a=JS.T.getTokenFromName(e.trim().toLowerCase());var f=null==a?0:a.tok,j=JS.T.tokAttr(f,
12288);a=J.console.GenericConsole.splitCommandLine(c);var h=null;if(!b&&('"'==g.charAt(0)||"'"==g.charAt(0)))b=g.charAt(0),JU.PT.trim(g,"\"'"),g=JU.PT.trim(a[2],"\"'"),h=this.nextFileName(g,this.nTab),null!=h&&(h=a[0]+a[1]+b+h+b);else{h=null;if(!b&&(g=e,d||a[2].startsWith("$")||JS.T.isIDcmd(f)||j))h=new java.util.Hashtable,this.vwr.getObjectMap(h,d||j?"{":a[2].startsWith("$")?"$":"0");h=JS.T.completeCommand(h,e.equalsIgnoreCase("set "),b,b?a[1]:a[2],this.nTab);h=a[0]+(null==h?g:b?h:a[1]+h)}return null==
h||h.equals(c)?null:h},"~S");e(c$,"doAction",function(a){if(a===this.runButton)this.execute(null);else if(a===this.editButton)this.vwr.getProperty("DATA_API","scriptEditor",null);else if(a===this.historyButton)this.clearContent(this.vwr.getSetHistory(2147483647));else if(a===this.stateButton)this.clearContent(this.vwr.getStateInfo());else if(a===this.clearInButton){this.input.setText("");return}a===this.clearOutButton?this.output.setText(""):a===this.loadButton?this.vwr.loadInlineAppend(this.input.getText(),
!1):this.isMenuItem(a)&&this.execute(a.getName())},"~O");e(c$,"execute",function(a){var c=null==a?this.input.getText():a;null==a&&this.input.setText(null);a=this.vwr.script(c+"\u0001## EDITOR_IGNORE ##");null!=a&&!a.equals("pending")&&this.outputMsg(a)},"~S");e(c$,"destroyConsole",function(){this.vwr.isApplet()&&this.vwr.getProperty("DATA_API","getAppConsole",Boolean.FALSE)});c$.setAbstractButtonLabels=e(c$,"setAbstractButtonLabels",function(a,c){for(var b,d=a.keySet().iterator();d.hasNext()&&((b=
d.next())||1);){var g=a.get(b),e=c.get(b);if(b.indexOf("Tip")==b.length-3)g.setToolTipText(c.get(b));else{var f=J.console.GenericConsole.getMnemonic(e);" "!=f&&g.setMnemonic(f);e=J.console.GenericConsole.getLabelWithoutMnemonic(e);g.setText(e)}}},"java.util.Map,java.util.Map");c$.getLabelWithoutMnemonic=e(c$,"getLabelWithoutMnemonic",function(a){if(null==a)return null;var c=a.indexOf("&");return-1==c?a:a.substring(0,c)+(c<a.length-1?a.substring(c+1):"")},"~S");c$.getMnemonic=e(c$,"getMnemonic",function(a){if(null==
a)return" ";var c=a.indexOf("&");return-1==c||c==a.length-1?" ":a.charAt(c+1)},"~S");c$.map=e(c$,"map",function(a,c,b,d){b=J.console.GenericConsole.getMnemonic(b);" "!=b&&a.setMnemonic(b);d.put(c,a)},"~O,~S,~S,java.util.Map");f(c$,"notifyEnabled",function(a){switch(a){case J.c.CBK.ECHO:case J.c.CBK.MEASURE:case J.c.CBK.MESSAGE:case J.c.CBK.PICK:return!0}return!1},"J.c.CBK");f(c$,"getText",function(){return this.output.getText()});f(c$,"sendConsoleEcho",function(a){null==a&&(this.updateLabels(),this.outputMsg(null),
a=this.defaultMessage);this.outputMsg(a)},"~S");e(c$,"outputMsg",function(a){null==a||0==a.length?this.output.setText(""):("\n"!=a.charAt(a.length-1)&&(a+="\n"),this.output.append(a))},"~S");e(c$,"clearContent",function(a){this.output.setText(a)},"~S");f(c$,"sendConsoleMessage",function(a){null!=a&&this.output.getText().startsWith(this.defaultMessage)&&this.outputMsg(null);this.outputMsg(a)},"~S");f(c$,"notifyCallback",function(a,c){var b=null==c||null==c[1]?null:c[1].toString();switch(a){case J.c.CBK.ECHO:this.sendConsoleEcho(b);
break;case J.c.CBK.MEASURE:var d=c[3];0<=d.indexOf("Picked")||0<=d.indexOf("Sequence")?this.sendConsoleMessage(b):0<=d.indexOf("Completed")&&this.sendConsoleEcho(b.substring(b.lastIndexOf(",")+2,b.length-1));break;case J.c.CBK.MESSAGE:this.sendConsoleMessage(null==c?null:b);break;case J.c.CBK.PICK:this.sendConsoleMessage(b)}},"J.c.CBK,~A");f(c$,"setCallbackFunction",function(){},"~S,~S");f(c$,"zap",function(){});e(c$,"recallCommand",function(a){a=this.vwr.getSetHistory(a?-1:1);null!=a&&this.input.setText(a)},
"~B");e(c$,"processKey",function(a,c,b){var d=0;switch(c){case 401:switch(a){case 9:c=this.input.getText();if(c.endsWith("\n")||c.endsWith("\t"))return 0;d=1;if(this.input.getCaretPosition()==c.length)return a=this.completeCommand(c),null!=a&&this.input.setText(a.$replace("\t"," ")),this.nTab++,d;break;case 27:d=1,this.input.setText("")}this.nTab=0;if(10==a&&!b)return this.execute(null),d;if(38==a||40==a)return this.recallCommand(38==a),d;break;case 402:if(10==a&&!b)return d}return d|2},"~N,~N,~B");
c$.splitCommandLine=e(c$,"splitCommandLine",function(a){var c=Array(4),b=!1,d=!1,e=!1;if(0==a.length)return null;for(var f=-1,m=0,j=0,h=0,l,k=0;k<a.length;k++){switch(l=a.charAt(k)){case '"':!e&&!b&&(d=!d)&&(f=j=k);break;case "'":!e&&!d&&(b=!b)&&(f=j=k);break;case "\\":e=!e;continue;case " ":!e&&(!b&&!d)&&(j=k+1,f=-1);break;case ";":!b&&!d&&(m=j=k+1,f=-1,h=0);break;case "{":case "}":!b&&!d&&(h+="{"==l?1:-1,j=k+1,f=-1);break;default:!b&&!d&&(f=-1)}e=!1}c[0]=a.substring(0,m);c[1]=j==m?a.substring(m):
a.substring(m,j>f?j:f);c[2]=j==m?null:a.substring(j);c[3]=0<h?"{":null;return c},"~S")});l("J.consolejs");n(["J.console.GenericConsole"],"J.consolejs.AppletConsole",null,function(){c$=q(function(){this.jsConsole=null;p(this,arguments)},J.consolejs,"AppletConsole",J.console.GenericConsole);r(c$,function(){t(this,J.consolejs.AppletConsole,[])});f(c$,"start",function(a){this.setViewer(a);this.setLabels();this.displayConsole()},"JV.Viewer");f(c$,"layoutWindow",function(){this.jsConsole=new Jmol.Console.JSConsole(this);
this.setTitle()},"~S");f(c$,"setTitle",function(){this.jsConsole&&this.jsConsole.setTitle(this.getLabel("title"))});f(c$,"setVisible",function(a){this.jsConsole.setVisible(a)},"~B");f(c$,"setButton",function(a){return new Jmol.Console.Button(a)},"~S");f(c$,"dispose",function(){this.setVisible(!1)});f(c$,"isMenuItem",function(){return!1},"~O");f(c$,"getScriptEditor",function(){return null});f(c$,"nextFileName",function(){return null},"~S,~N")})})(Clazz,Clazz.doubleToInt,Clazz.declarePackage,Clazz.instanceOf,
Clazz.load,Clazz.instantialize,Clazz.decorateAsClass,Clazz.floatToInt,Clazz.makeConstructor,Clazz.defineEnumConstant,Clazz.exceptionOf,Clazz.newIntArray,Clazz.defineStatics,Clazz.newFloatArray,Clazz.declareType,Clazz.prepareFields,Clazz.superConstructor,Clazz.newByteArray,Clazz.declareInterface,Clazz.p0p,Clazz.pu$h,Clazz.newShortArray,Clazz.innerTypeInstance,Clazz.isClassDefined,Clazz.prepareCallback,Clazz.newArray,Clazz.castNullAs,Clazz.floatToShort,Clazz.superCall,Clazz.decorateAsType,Clazz.newBooleanArray,
Clazz.newCharArray,Clazz.implementOf,Clazz.newDoubleArray,Clazz.overrideConstructor,Clazz.clone,Clazz.doubleToShort,Clazz.getInheritedLevel,Clazz.getParamsType,Clazz.isAF,Clazz.isAI,Clazz.isAS,Clazz.isASS,Clazz.isAP,Clazz.isAFloat,Clazz.isAII,Clazz.isAFF,Clazz.isAFFF,Clazz.tryToSearchAndExecute,Clazz.getStackTrace,Clazz.inheritArgs,Clazz.alert,Clazz.defineMethod,Clazz.overrideMethod,Clazz.declareAnonymous,Clazz.cloneFinals);
